### ISSUE TITLE
Doesn't even import. Am I stupid and missing something obvious or what?

### ISSUE THREAD

**Issue by Lenikuf** [jwcarlson01/bvPlayer#2]
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from bvPlayer import bvPlayer
  File "/home/runner/yt/venv/lib/python3.8/site-packages/bvPlayer/__init__.py", line 1, in <module>
    from .bvPlayer import bvPlayer
  File "/home/runner/yt/venv/lib/python3.8/site-packages/bvPlayer/bvPlayer.py", line 2, in <module>
    from . import VideoPlayer
  File "/home/runner/yt/venv/lib/python3.8/site-packages/bvPlayer/VideoPlayer.py", line 1, in <module>
    import cv2
  File "/home/runner/yt/venv/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by jwcarlson01** [comment]
It looks like you're having an opencv error, this error seems to appear when you try to run opencv on a docker container. Here's an article that may help:

https://itsmycode.com/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directory/

Let me know what you're trying to run the package on if the issue persists, I haven't experienced this issue either on Windows or Linux VMs, but I've never used docker containers.
